### PR TITLE
Remove config import from init to fix scaffold usage

### LINKED ISSUE #370: config import fails when using V2 scaffolding
At:
https://github.com/drivendataorg/cookiecutter-data-science/blob/master/%7B%7B%20cookiecutter.repo_name%20%7D%7D/%7B%7B%20cookiecutter.module_name%20%7D%7D/__init__.py#L1

Should be `from {{ cookiecutter.module_name }} import config`  # noqa: F401

------------

### Discussed in https://github.com/drivendataorg/cookiecutter-data-science/discussions/369

<div type='discussions-op-text'>

<sup>Originally posted by **wrighteap** May 27, 2024</sup>
Hi!

New cookiecutter user here. I just tried using your new v2 release.

I created a project project, repo repo and module module, using the code scaffold option. I selected conda as my environment manager, and requirements.txt for my dependency file. 

pip list shows the package module installed at /path/to/repo. When I try to import module, I get a ModuleNotFoundError: No module named 'config', due to the import config under module/__init__.py -- Is this a design choice to invite me to add /path/to/repo/module to sys path or to modify the config directly?

Sorry in advance if the question is inane or lacking in detail - happy to be told so or asked for additional information.</div>

### PR DESCRIPTION
**Pull request by pjbull**
- Remove config import from `__init__.py` (not needed and also breaks since it is there in non-scaffold scenario)
 - Refactor some repeated code
 - Add import and import config tests
 - Add changelog

Closes #370

### CODE REVIEW

**Comment by jayqi** [comment]
> not needed

The main thing that happens in `config` right now that is valuable to auto-execute is this bit:

https://github.com/drivendataorg/cookiecutter-data-science/blob/bbfa1511ff724731ddd482bcffcd62fb1e6b1b83/%7B%7B%20cookiecutter.repo_name%20%7D%7D/%7B%7B%20cookiecutter.module_name%20%7D%7D/config.py#L24-L32

**Comment by pjbull** [comment]
> The main thing that happens in config right now that is valuable to auto-execute is this bit:

Ah, that's a good point. Added back in.

**Review by jayqi — APPROVED** [review]

**Review by chrisjkuch — APPROVED** [review]
LGTM!

Just summarizing for my own understanding / posterity:

* We weren't appropriately removing `import config` from `__init__.py` when we removed all the boilerplate code, which failed at import time because `config.py` no longer existed
* When the boilerplate was present, we weren't importing `config` from the right place leading to an import error
* We now import the config from the right place and remove it when boilerplate is removed, and we test that both of those work as expected in the live tests

**Comment by pjbull** [comment]
> Just summarizing for my own understanding / posterity:

Nailed it! 🔨

**Pull request merged**
